const crypto       = require('crypto');
const axios        = require('axios');
const { v7: uuidv7 } = require('uuid');
const User           = require('../models/User');
const OAuthState     = require('../models/OAuthState');
const { issueTokens, rotateRefreshToken, revokeAllUserTokens } = require('../utils/tokenService');

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Generates a cryptographically random string of the given byte length,
 * encoded as base64url (URL-safe, no padding).
 * Used to generate both `state` and `code_verifier`.
 *
 * @param {number} bytes
 * @returns {string}
 */
function randomBase64url(bytes = 32) {
  return crypto
    .randomBytes(bytes)
    .toString('base64url'); // base64url = base64 without +, /, = characters
}

/**
 * Derives code_challenge from code_verifier using SHA-256.
 * This is the S256 method required by PKCE.
 *
 * @param {string} verifier
 * @returns {string}
 */
function sha256Base64url(verifier) {
  return crypto
    .createHash('sha256')
    .update(verifier)
    .digest('base64url');
}

// ── GET /auth/github ──────────────────────────────────────────────────────────

/**
 * Initiates the GitHub OAuth flow.
 *
 * For browser (web): generates state, stores it, redirects to GitHub.
 * For CLI: the CLI generates its own state + code_challenge and passes them
 *          as query parameters. Backend stores them and redirects to GitHub
 *          with code_challenge included.
 *
 * Query params (CLI only):
 *   state          — generated by CLI
 *   code_challenge — SHA-256 hash of the CLI's code_verifier
 */
async function initiateOAuth(req, res, next) {
  try {
    const { state: cliState, code_challenge: cliChallenge, source } = req.query;

    // Use CLI-provided state or generate one for browser flow
    const state          = cliState || randomBase64url(32);
    const code_challenge = cliChallenge || null;
    const flowSource     = source === 'cli' ? 'cli' : 'web';

    // Store state + code_challenge temporarily in DB
    await OAuthState.create({
      state,
      code_challenge,
      source: flowSource,
    });

    // Build GitHub authorization URL
    const params = new URLSearchParams({
      client_id:    process.env.GITHUB_CLIENT_ID,
      redirect_uri: process.env.GITHUB_CALLBACK_URL,
      scope:        'read:user user:email',
      state,
    });

    // Include PKCE challenge for CLI flows
    if (code_challenge) {
      params.set('code_challenge',        code_challenge);
      params.set('code_challenge_method', 'S256');
    }

    return res.redirect(`https://github.com/login/oauth/authorize?${params}`);

  } catch (err) {
    next(err);
  }
}

// ── GET /auth/github/callback ─────────────────────────────────────────────────

/**
 * Handles the GitHub OAuth callback.
 *
 * Steps:
 *  1. Validate state — matches what was stored at flow start
 *  2. Exchange code for GitHub access token
 *  3. Fetch GitHub user profile
 *  4. Create or update user in our DB
 *  5. Issue our own access + refresh tokens
 *  6. Return tokens (CLI: JSON | Web: redirect with cookie)
 */
async function handleCallback(req, res, next) {
  try {
    const { code, state } = req.query;

    if (!code || !state) {
      return res.status(400).json({ status: 'error', message: 'Missing code or state' });
    }

    // ── 1. Validate state ───────────────────────────────────────────────────
    const storedState = await OAuthState.findOne({ state });
    if (!storedState) {
      return res.status(400).json({ status: 'error', message: 'Invalid or expired state' });
    }

    // Delete immediately — one-time use
    await OAuthState.deleteOne({ state });

    // ── 2. Exchange code for GitHub access token ────────────────────────────
    const tokenRes = await axios.post(
      'https://github.com/login/oauth/access_token',
      {
        client_id:     process.env.GITHUB_CLIENT_ID,
        client_secret: process.env.GITHUB_CLIENT_SECRET,
        code,
        redirect_uri:  process.env.GITHUB_CALLBACK_URL,
        // Include code_verifier for PKCE flows — GitHub verifies it matches the challenge
        ...(storedState.code_challenge && {
          code_verifier: req.query.code_verifier,
        }),
      },
      { headers: { Accept: 'application/json' } }
    );

    const githubAccessToken = tokenRes.data.access_token;
    if (!githubAccessToken) {
      return res.status(400).json({ status: 'error', message: 'GitHub token exchange failed' });
    }

    // ── 3. Fetch GitHub user profile ────────────────────────────────────────
    const [userRes, emailRes] = await Promise.all([
      axios.get('https://api.github.com/user', {
        headers: { Authorization: `Bearer ${githubAccessToken}` },
      }),
      axios.get('https://api.github.com/user/emails', {
        headers: { Authorization: `Bearer ${githubAccessToken}` },
      }).catch(() => ({ data: [] })), // emails may be private — fail gracefully
    ]);

    const ghUser  = userRes.data;
    const primary = emailRes.data.find?.(e => e.primary)?.email || ghUser.email || null;

    // ── 4. Create or update our user ────────────────────────────────────────
    let user = await User.findOne({ github_id: String(ghUser.id) });

    if (!user) {
      // First login — create the user
      user = await User.create({
        id:            uuidv7(),
        github_id:     String(ghUser.id),
        username:      ghUser.login,
        email:         primary,
        avatar_url:    ghUser.avatar_url,
        role:          'analyst',         // default per spec
        is_active:     true,
        last_login_at: new Date(),
        created_at:    new Date(),
      });
    } else {
      // Returning user — update profile info and last_login
      user.username      = ghUser.login;
      user.email         = primary;
      user.avatar_url    = ghUser.avatar_url;
      user.last_login_at = new Date();
      await user.save();
    }

    if (!user.is_active) {
      return res.status(403).json({ status: 'error', message: 'Account is deactivated' });
    }

    // ── 5. Issue our tokens ─────────────────────────────────────────────────
    const tokens = await issueTokens(user);

    // ── 6. Return tokens ────────────────────────────────────────────────────
    if (storedState.source === 'cli') {
      // CLI flow — return JSON directly so the CLI can capture it
      return res.status(200).json({
        status:        'success',
        access_token:  tokens.access_token,
        refresh_token: tokens.refresh_token,
        user: {
          id:         user.id,
          username:   user.username,
          role:       user.role,
          avatar_url: user.avatar_url,
        },
      });
    }

    // Web flow — set HTTP-only cookies and redirect to dashboard
    res.cookie('access_token', tokens.access_token, {
      httpOnly: true,
      secure:   process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      maxAge:   3 * 60 * 1000, // 3 minutes
    });
    res.cookie('refresh_token', tokens.refresh_token, {
      httpOnly: true,
      secure:   process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      maxAge:   5 * 60 * 1000, // 5 minutes
    });

    // Redirect to web portal dashboard
    return res.redirect(`${process.env.WEB_PORTAL_URL}/dashboard`);

  } catch (err) {
    next(err);
  }
}

// ── POST /auth/refresh ────────────────────────────────────────────────────────

/**
 * Rotates a refresh token — invalidates the old one, issues a fresh pair.
 * Supports both JSON body (CLI) and cookies (web).
 */
async function refreshTokens(req, res, next) {
  try {
    // Accept from JSON body (CLI) or from HTTP-only cookie (web)
    const rawToken = req.body?.refresh_token || req.cookies?.refresh_token;

    if (!rawToken) {
      return res.status(400).json({ status: 'error', message: 'Refresh token required' });
    }

    const tokens = await rotateRefreshToken(rawToken, User);

    // For web: update cookies
    if (req.cookies?.refresh_token) {
      res.cookie('access_token', tokens.access_token, {
        httpOnly: true,
        secure:   process.env.NODE_ENV === 'production',
        sameSite: 'lax',
        maxAge:   3 * 60 * 1000,
      });
      res.cookie('refresh_token', tokens.refresh_token, {
        httpOnly: true,
        secure:   process.env.NODE_ENV === 'production',
        sameSite: 'lax',
        maxAge:   5 * 60 * 1000,
      });
    }

    return res.status(200).json({
      status:        'success',
      access_token:  tokens.access_token,
      refresh_token: tokens.refresh_token,
    });

  } catch (err) {
    if (err.statusCode) {
      return res.status(err.statusCode).json({ status: 'error', message: err.message });
    }
    next(err);
  }
}

// ── POST /auth/logout ─────────────────────────────────────────────────────────

/**
 * Revokes all refresh tokens for the authenticated user.
 * Clears cookies for web sessions.
 */
async function logout(req, res, next) {
  try {
    // authenticate middleware already verified the access token
    await revokeAllUserTokens(req.user.id);

    // Clear web cookies
    res.clearCookie('access_token');
    res.clearCookie('refresh_token');

    return res.status(200).json({ status: 'success', message: 'Logged out successfully' });

  } catch (err) {
    next(err);
  }
}

// ── GET /auth/me ──────────────────────────────────────────────────────────────

/**
 * Returns the authenticated user's profile.
 * Used by CLI whoami and web portal account page.
 */
async function getMe(req, res) {
  return res.status(200).json({
    status: 'success',
    data: {
      id:            req.user.id,
      username:      req.user.username,
      email:         req.user.email,
      avatar_url:    req.user.avatar_url,
      role:          req.user.role,
      last_login_at: req.user.last_login_at,
      created_at:    req.user.created_at,
    },
  });
}

module.exports = { initiateOAuth, handleCallback, refreshTokens, logout, getMe };
