/**
 * Country name → ISO 3166-1 alpha-2 lookup.
 *
 * Entries are sorted longest-first so multi-word names (e.g. "south africa")
 * always match before shorter substrings (e.g. "africa").
 */

const RAW_MAP = {
  // ── Africa ────────────────────────────────────────────────────────────────
  'nigeria':                          'NG',
  'ghana':                            'GH',
  'kenya':                            'KE',
  'angola':                           'AO',
  'benin':                            'BJ',
  'cameroon':                         'CM',
  'ethiopia':                         'ET',
  'egypt':                            'EG',
  'south africa':                     'ZA',
  'tanzania':                         'TZ',
  'uganda':                           'UG',
  'rwanda':                           'RW',
  'senegal':                          'SN',
  'mali':                             'ML',
  "cote d'ivoire":                    'CI',
  "côte d'ivoire":                    'CI',
  'ivory coast':                      'CI',
  'mozambique':                       'MZ',
  'zambia':                           'ZM',
  'zimbabwe':                         'ZW',
  'togo':                             'TG',
  'sierra leone':                     'SL',
  'liberia':                          'LR',
  'guinea-bissau':                    'GW',
  'equatorial guinea':                'GQ',
  'guinea':                           'GN',
  'somalia':                          'SO',
  'sudan':                            'SD',
  'south sudan':                      'SS',
  'chad':                             'TD',
  'democratic republic of the congo': 'CD',
  'democratic republic of congo':     'CD',
  'republic of the congo':            'CG',
  'republic of congo':                'CG',
  'congo republic':                   'CG',
  'drc':                              'CD',
  'congo':                            'CG',
  'gabon':                            'GA',
  'botswana':                         'BW',
  'namibia':                          'NA',
  'malawi':                           'MW',
  'madagascar':                       'MG',
  'mauritius':                        'MU',
  'morocco':                          'MA',
  'tunisia':                          'TN',
  'algeria':                          'DZ',
  'libya':                            'LY',
  'niger':                            'NE',
  'burkina faso':                     'BF',
  'burkina':                          'BF',
  'central african republic':         'CF',
  'car':                              'CF',
  'eritrea':                          'ER',
  'djibouti':                         'DJ',
  'comoros':                          'KM',
  'cabo verde':                       'CV',
  'cape verde':                       'CV',
  'sao tome and principe':            'ST',
  'seychelles':                       'SC',
  'lesotho':                          'LS',
  'eswatini':                         'SZ',
  'swaziland':                        'SZ',
  'burundi':                          'BI',
  'mauritania':                       'MR',
  'the gambia':                       'GM',
  'gambia':                           'GM',
  // ── Americas ──────────────────────────────────────────────────────────────
  'united states of america':         'US',
  'united states':                    'US',
  'usa':                              'US',
  'us':                               'US',
  'canada':                           'CA',
  'mexico':                           'MX',
  'brazil':                           'BR',
  'argentina':                        'AR',
  'colombia':                         'CO',
  'chile':                            'CL',
  'peru':                             'PE',
  'venezuela':                        'VE',
  'ecuador':                          'EC',
  'bolivia':                          'BO',
  'paraguay':                         'PY',
  'uruguay':                          'UY',
  'guyana':                           'GY',
  'suriname':                         'SR',
  'cuba':                             'CU',
  'haiti':                            'HT',
  'dominican republic':               'DO',
  'jamaica':                          'JM',
  // ── Europe ────────────────────────────────────────────────────────────────
  'united kingdom':                   'GB',
  'great britain':                    'GB',
  'england':                          'GB',
  'uk':                               'GB',
  'france':                           'FR',
  'germany':                          'DE',
  'italy':                            'IT',
  'spain':                            'ES',
  'portugal':                         'PT',
  'netherlands':                      'NL',
  'belgium':                          'BE',
  'switzerland':                      'CH',
  'austria':                          'AT',
  'sweden':                           'SE',
  'norway':                           'NO',
  'denmark':                          'DK',
  'finland':                          'FI',
  'poland':                           'PL',
  'russia':                           'RU',
  'ukraine':                          'UA',
  'greece':                           'GR',
  'turkey':                           'TR',
  'romania':                          'RO',
  'hungary':                          'HU',
  'czech republic':                   'CZ',
  'czechia':                          'CZ',
  'slovakia':                         'SK',
  'serbia':                           'RS',
  'croatia':                          'HR',
  'ireland':                          'IE',
  // ── Asia / Oceania ────────────────────────────────────────────────────────
  'china':                            'CN',
  'india':                            'IN',
  'japan':                            'JP',
  'south korea':                      'KR',
  'north korea':                      'KP',
  'korea':                            'KR',
  'indonesia':                        'ID',
  'pakistan':                         'PK',
  'bangladesh':                       'BD',
  'philippines':                      'PH',
  'vietnam':                          'VN',
  'thailand':                         'TH',
  'malaysia':                         'MY',
  'singapore':                        'SG',
  'myanmar':                          'MM',
  'sri lanka':                        'LK',
  'nepal':                            'NP',
  'afghanistan':                      'AF',
  'iran':                             'IR',
  'iraq':                             'IQ',
  'saudi arabia':                     'SA',
  'united arab emirates':             'AE',
  'uae':                              'AE',
  'israel':                           'IL',
  'jordan':                           'JO',
  'lebanon':                          'LB',
  'kuwait':                           'KW',
  'qatar':                            'QA',
  'bahrain':                          'BH',
  'oman':                             'OM',
  'yemen':                            'YE',
  'australia':                        'AU',
  'new zealand':                      'NZ',
};

// Pre-sort longest entry first so greedy matching works correctly
const SORTED_ENTRIES = Object.entries(RAW_MAP)
  .sort((a, b) => b[0].length - a[0].length);

/**
 * Given the text extracted after "from" / "in" in a query,
 * return the ISO-2 code or null if not found.
 *
 * @param {string} text
 * @returns {string|null}
 */
function lookupCountryCode(text) {
  const t = text.trim().toLowerCase();
  for (const [name, code] of SORTED_ENTRIES) {
    if (t === name || t.startsWith(name + ' ') || t.startsWith(name)) {
      return code;
    }
  }
  return null;
}

module.exports = { lookupCountryCode };
